### ISSUE TITLE
Anonymous Users

### ISSUE THREAD

**Issue by bibliotechie** [bibliotechie/antithesis-meta#2]
We want strong support for anonymous users -- i.e., we want most site features to work without an account, with some differences in behavior.

- [ ] Automatically create an anonymous user in the database.
- [ ] Design a good UI for being logged in as anonymous by default.
- [ ] Add some kind of privacy-friendly and accessible captcha system.
- [ ] Disable or localize all settings for anonymous users.
- [ ] Disable inappropriate features for anonymous users.
  - [ ] highlights
  - [ ] deleting
  - [ ] editing
- [ ] Get moderation working well enough to handle abuse.
